### ISSUE TITLE
Named routes with parameters do not get translated

### ISSUE THREAD

**Issue by jensb** [enriclluelles/route_translator#105]
It seems that parameters in named URLs are not permitted (ie. do not get translated). 
Here is an example, please try this out and report whether it works (and what to do if it does not):

``` ruby
# routes.rb
ActionDispatch::Routing::SEPARATORS << "-"
Rails.application.routes.draw do
  constraints :format => /html|js|json/ do
    localized do
      get 'foo-bar-baz', as: foobarbaz, some_param: "value"        # This works fine if a translation is available.
      get 'foo-:bar-:baz', as: foobarbazparams        # This will not find a translation, no matter what is provided in the I18n configuration.
    end
  end
end
```

For the second example, I tried `foo:` and `foo-:bar-:baz` as keys for I18n, but no works.
What's more, an URL like `foobarbazparams_path(bar: "Some", baz: "Text") will be represented like

```
foobar.com/foo-Some-Text
```

without route_translator (which works as expected), but be modified to look like

```
foobar.com/foo-?bar=Some&baz=Text
```

if route_translator is enabled - even for the default language.

How can I fix this? Thanks!

**Comment by mattvleming** [comment]
I too am experiencing this issue. The bug seems to come from here: https://github.com/enriclluelles/route_translator/blob/master/lib/route_translator/translator.rb#L118-L125 `foo-:bar-:baz` will be passed into `#translate_path_segment`, and `foo-` will be returned.

The issue seems to be the method assumes [when there is a param in a route, it will be at the beginning]((https://github.com/enriclluelles/route_translator/blob/master/lib/route_translator/translator.rb#L119), i.e. `get ':bar'`, not `get 'foo-:bar'`.

@tagliala Do you have any thoughts on changing `TRANSLATABLE_SEGMENT ` so it matches params too [here](https://github.com/enriclluelles/route_translator/blob/master/lib/route_translator/translator.rb#L122)? This way the string passed into `#translate_string` [here](https://github.com/enriclluelles/route_translator/blob/master/lib/route_translator/translator.rb#L124) is `foo-:bar` instead of `foo-`. One would then have to translate `foo-:bar` in `routes.yml`:

```
# routes.yml

es:
  routes:
    'foo-:bar': 'translated-:bar'
```

**Comment by jensb** [comment]
Changing translations in this way would be fine and is actually the way I have used `i18n_routes` before (which unfortunately is unmaintained and I have failed to patch it for Rails 4.2.x after many attempts). I would very much appreciate this!

**Comment by tagliala** [comment]
@mattvleming a failing spec and a PR would be very welcomed

**Comment by tagliala** [comment]
Sorry, I will not support custom `ActionDispatch::Routing::SEPARATORS`

**Comment by davideghz** [comment]
Hello, trying again 4 years later :) is there any chance named routes with parameters at the end will be supported?
For SEO reason many routes of one of my project are built like that. Is there any workaround I can implement to handle it?

**Comment by tagliala** [comment]
> is there any chance named routes with parameters at the end will be supported?

Hi, even if I understand that Route Translator should take `ActionDispatch::Routing::SEPARATORS` into account, I will not personally implement this feature for at least the following reasons:

- I did not need this feature
- I do not use this gem in production environments since 2015 or something like that
- This feature does not seem trivial
- Implementing a new feature requires time after the release for bug fixes

The above points will eventually result in a situation like #178, where I need to decide between a broken implementation and the removal of the feature

> Is there any workaround I can implement to handle it?

Yes, PR #112 should contain a fix for this issue, feel free to monkey patch RouteTranslator
