### ISSUE TITLE
Take into account namespace

### ISSUE THREAD

**Issue by rugginoso** [enriclluelles/route_translator#120]
I have the following routes:

``` ruby
  localized do
    namespace :blog do
        get '/categories/:category_id', to: 'posts#index', as: :category_posts
    end

    scope :history do
      namespace :timeline do
        resources :categories, only: :show
      end
   end
 end
```

Is there a way to differently translate "categories"?

**Comment by tagliala** [comment]
For anyone interested in this feature, I've started a branch based on #148.

https://github.com/enriclluelles/route_translator/tree/feature/namespaced-routes

### I can't merge because

1. https://codeclimate.com/github/enriclluelles/route_translator/compare/feature/namespaced-routes#ratings

2. I really don't like [this assignment](https://github.com/enriclluelles/route_translator/blob/feature/namespaced-routes/lib/route_translator/translator/path/segment.rb#L21)

```rb
res =
  if I18n.translate(str, opts.merge(exception_handler: handler)).is_a?(I18n::MissingTranslation)
    I18n.translate(str, opts.merge(scope: :routes).merge(fallback_options(str, locale)).merge(exception_handler: nil))
  else
    I18n.translate(str, opts.merge(exception_handler: handler))
  end
```

Any help would be appreciated

**Comment by tagliala** [comment]
Closing here.

There is an updated version of this PR @ https://github.com/enriclluelles/route_translator/tree/feature/namespaced-routes
