### ISSUE TITLE
Avoid duplicate routes in host locales

### ISSUE THREAD

**Issue by tagliala** [enriclluelles/route_translator#171]
Hi, please give a try to the new version of the gem, I've just released an alpha version.

Breaking changes are related to the **Host-based Locale** feature and **Engine** support:
- `verify_host_path_consistency` is a default and it cannot be disabled (#167) (#91)
- Avoid duplicate routes in host locales (eg: `/route` and `/en/route` on your `en` domain) (#87)

In other words, you can use `host_locales` if you don't have a main domain like `www.example.com` and your subdomains have one language for each one *it.example.com*, *es.example.com*.

If you have special needs (eg: main domain with all languages, subdomains with separate languages) please go for a custom solution.

The whole `native_path` stuff has been removed, each localized route only work for its own domain.

Please use this thread to report issues and feedbacks

---

Having multiple languages for the same subdomain is out of the Route Translator's scope.

Anyway, there is a simple workaround to restore this feautre: https://github.com/enriclluelles/route_translator/issues/171#issuecomment-324083093

**Comment by tagliala** [comment]
Is anybody using this version?

**Comment by josefsj3m** [comment]
Hi tagliala,

I am using verson 5.5 to implement a custom locale identification, first based on url, if it is absent based on cookie, if it is absent based on browser language and based on domain at last. 

The rails app is serving two domains, domain.com and domain.com.br, and the locales en, pt-br and es.  I've tried to implement the two domains with all languages using host_locales, but I couldn't  do it because when I set I18n.default_locale = :'pt-BR' the gem doesn't gererate the route domain.com/pt-BR/something, on the other hand, setting I18n.default_locale = :en there is no route like domain.com.br/en/something. I think it is strange an url like this domain.com/empresas or domain.com.br/companies.

There is no problem with es locale because the host_locales doesn't have an entry *.es, so the gem generates the routes domain.com/es/empresas and dmain.com.br/es/empresas. Is it suppose to be the right behavior ? Or I am doing something wrong.

I can't upgrade to 6.0 because it has a completely different approach and will break my code. Is it possible to maint the current behavior in 6.0 ?

Regards,
Jose Fernando

**Comment by tagliala** [comment]
> Is it possible to maint the current behavior in 6.0 ?

Unfortunately the whole point of the 6.0 is that breaking change

I would like to fix #87 and simplify the host locales feature for the basic use case (one domain per language).

If there is a way to save locales without host, a PR would be appreciated

Anyway, I could decide to not release 6.0 at all 🤷‍♂️

**Comment by josefsj3m** [comment]
I guess the main point here is duplicated content and how to avoid it. Reading some google pages, Multi-regional and multilingual sites (https://support.google.com/webmasters/answer/182192?hl=en#3) and Use hreflang for language and regional URLs (https://support.google.com/webmasters/answer/189077) , I think we can have one domain and multiple languages since we provide an hreflang in the head with the prefered alternate language. This approach 5.5 version already has.

So, one domain per language sure avoid content duplication, but forcing it when using host_locales I think limit to one use case. Please correct me if I am wrong, but using verify_host_path_consistency = true in version 5.5 avoid content duplication.

In my use case, two domains and multiple languages, I am writing a custom code right now because a get the locale not only from host, take a look at this and, please, feel free to comment. I am skipping :set_locale_from_url and using do_check_locale instead:

```
def do_check_locale(&block)
    new_loc = I18n.default_locale
    loc = locale_in_url?
    if loc.nil?
      if valid_language_cookie?
        # Language cookie is valid, use it.
        new_loc = cookies[:eol_language].to_s.to_sym
      else
        # There is no valid language cookie try the browser language
        brw_loc = locale_from_browser
        if !brw_loc.nil?
          # Use the browser locale. 
          new_loc = brw_loc
        else
          # Could not get the browser language use the locale from domain
          loc_domain = current_site.domains_to_locale[request.domain.to_sym]
          unless loc_domain.nil?
            # Use locale assigned to the domain
            new_loc = loc_domain
          end
        end
      end
    else
      # The url contains the locale, use it.
      new_loc = loc
    end
  rescue => e
    # Avoid the request crash, log the error and ensure the I18n.with_locale
    loc_error = ChangeLocaleError.new("Error: Module: ApplicationHelper, Method: do_check_locale, Msg: #{e.message}", e)
    log_and_notify_error(loc_error)
  ensure
     # Locale changes only apply to the current request by saving its original values.
     original_default = I18n.default_locale
     original_locale = I18n.locale
     I18n.default_locale = new_loc
     I18n.locale = new_loc
     I18n.with_locale new_loc, &block
     I18n.default_locale = original_default
     I18n.locale = original_locale
  end
```
Regards,

**Comment by tagliala** [comment]
> Use hreflang for language and regional URLs

This is a good workaround and that is what I was using to avoid penalties

> Please correct me if I am wrong, but using verify_host_path_consistency = true in version 5.5 avoid content duplication.

Not entirely. It does not avoid both `/route` and `/en/route` routes on the same domain, and that leads to content duplication

Using the current behavior for 6.0 would be possible by customizing the `locale_from_host` section.

**Comment by tagliala** [comment]
E.g.:

Initializer
```rb
RouteTranslator.config do |config|
  config.hide_locale = true
end
```

application.rb
```rb
  # ...
  config.domain_language = {
    'it.lvh.me' => :it,
    'en.lvh.me' => :en,
    'de.lvh.me' => :de
  }
```

Application controller
```rb
  # ...
  skip_around_action :set_locale_from_url
  around_action :set_site_locale
  # ...
  
  def set_site_locale(&block)
    I18n.with_locale Rails.application.config.domain_language[request.host], &block
  end
```

This will allow to use multiple languages for each host, with all the duplication.

**Comment by josefsj3m** [comment]
Thanks,

I'll use custom solution with hreflang and redirects 301.

**Comment by tagliala** [comment]
@josefsj3m you're welcome. But it is not sure I'm going to release 6.0 at all. Things could change

**Comment by josefsj3m** [comment]
Yes, I know. What I am trying to do is a custom solution that is compliant with your development. I don't want to develop a route_translator from the ground, I have no time to do that.
I am working on that, and when I am acomplish it I will share the code.
Thanks a lot.

**Comment by tagliala** [comment]
I'm going to drop the engine support, because it is buggy and partial.

A proper engine support should preserve the `engine` helper (#166) and  should not duplicate :locale in paths (#173).

If there is someone that would contribute to this and submit a PR, please make sure that the above points are checked
